/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanli_khach_san.hoadon;
import java.sql.Date;
import java.util.ArrayList;

import com.toedter.calendar.DateUtil;
import com.toedter.calendar.JDateChooser;
import quanli_khach_san.Util.MyConvert;
import quanli_khach_san.dichvu.DichVu;
import quanli_khach_san.dichvu.DichVuDAO;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khanh
 */
/*SOHD                 INTEGER              NOT NULL,
   MAPHIEUTP            INTEGER              NOT NULL,
   MAPHIEUTDV           INTEGER,
   MANV                 INTEGER              NOT NULL,
   MAKM                 INTEGER,
   MAKH                 INTEGER              NOT NULL,
   NGAYHD               DATE,
   THANHTIEN            NUMBER(8,2),
   CONSTRAINT PK_HOADON PRIMARY KEY (SOHD)*/
public class HoaDonFrame extends javax.swing.JFrame {

    /**
     * Creates new form HoaDonFrame
     */
    private HoaDonDAO HDDAO = HDDAO = new HoaDonDAO();
    private ArrayList<HoaDon> list;
    public HoaDonFrame() {

        initComponents();
        reset();
    }



    private void reset() {


        list = HDDAO.queryAllHoaDon();
        pushDataToTable();

    }

    //Kéo data từ trong list lên table

    private void pushDataToTable() {
      String[] ColumnName = {"SOHD","MAPHIEUTP", "MAPHIEUTDV", "MANV","MAKM","MAKH","NGAYHD","THANHTIEN"};
        Object[][] Rows = new Object[list.size()][8];
        for (int i = 0; i < list.size(); i++) {
            Rows[i][0] = list.get(i).getSOHD();
            Rows[i][1] = list.get(i).getMAPHIEUTP();
            Rows[i][2] = list.get(i).getMAPHIEUTDV();
            Rows[i][3] = list.get(i).getMANV();
            Rows[i][4] = list.get(i).getMAKH();
            Rows[i][5] = list.get(i).getMAKH();
            Rows[i][6] = list.get(i).getNGAYHD();
            Rows[i][7] = list.get(i).getTHANHTIEN();
        }
        DefaultTableModel model = new DefaultTableModel(Rows, ColumnName);
        this.table.setModel(model);
    }
    private HoaDon creatNewHoaDon() {
        String sohd = txtSOHD.getText();
        String maphieutp = txtMAPHIEUTP.getText();
        String maphieutdv = txtMAPHIEUTDV.getText();
        String manv = txtMANV.getText();
        String makm = txtMAKM.getText();
        String makh = txtMAKH.getText();
        java.util.Date ngayhd=null;
        if(dateNGAYHD.getDate() != null ){
            java.util.Date utilStartDate = dateNGAYHD.getDate();
            java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
            ngayhd=sqlStartDate;
        }
        Integer thanhtien = MyConvert.parseStringToInt(txtTHANHTIEN.getText());
        return new HoaDon(sohd,maphieutp,maphieutdv,manv, makm,makh,ngayhd, thanhtien);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDV = new javax.swing.JPanel();
        tablePanel = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        mainPanel = new javax.swing.JPanel();
        titilePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        informationPanel = new javax.swing.JPanel();
        txtSOHD = new javax.swing.JTextField();
        lbSOHD = new javax.swing.JLabel();
        lbMAPHIEUTP = new javax.swing.JLabel();
        lbMAPHIEUTDV = new javax.swing.JLabel();
        txtMAPHIEUTDV = new javax.swing.JTextField();
        txtMAPHIEUTP = new javax.swing.JTextField();
        choosePanel = new javax.swing.JPanel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        addButton = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        editButton = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        removeButton = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        resetButton = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnSearch = new javax.swing.JButton();
        lbMAKM = new javax.swing.JLabel();
        txtMAKM = new javax.swing.JTextField();
        lbMANV = new javax.swing.JLabel();
        txtMANV = new javax.swing.JTextField();
        lbNGAYHD = new javax.swing.JLabel();
        dateNGAYHD = new com.toedter.calendar.JDateChooser();
        lbMAKH = new javax.swing.JLabel();
        txtMAKH = new javax.swing.JTextField();
        lbTHANHTIEN = new javax.swing.JLabel();
        txtTHANHTIEN = new javax.swing.JTextField();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));
        tablePanel.setBorder(null);
        tablePanel.setFocusable(false);
        tablePanel.setMinimumSize(new java.awt.Dimension(23, 23));
        tablePanel.setPreferredSize(new java.awt.Dimension(452, 402));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SOHD", "MAPHIEUTP", "MAPHIEUTDV", "MANV", "MAKM", "MAKH", "NGHD", "THANHTIEN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        tablePanel.setViewportView(table);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        titilePanel.setBackground(new java.awt.Color(40, 60, 82));
        titilePanel.setMaximumSize(new java.awt.Dimension(32767, 60));
        titilePanel.setMinimumSize(new java.awt.Dimension(0, 60));
        titilePanel.setPreferredSize(new java.awt.Dimension(716, 60));
        titilePanel.setLayout(new javax.swing.BoxLayout(titilePanel, javax.swing.BoxLayout.LINE_AXIS));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("QUẢN LÍ THÔNG TIN HOÁ ĐƠN");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titleLabel.setMaximumSize(new java.awt.Dimension(32000, 100));
        titleLabel.setMinimumSize(new java.awt.Dimension(408, 32));
        titleLabel.setPreferredSize(new java.awt.Dimension(408, 32));
        titilePanel.add(titleLabel);

        informationPanel.setBackground(new java.awt.Color(255, 255, 255));
        informationPanel.setMaximumSize(new java.awt.Dimension(32767, 300));
        informationPanel.setMinimumSize(new java.awt.Dimension(200, 280));
        informationPanel.setPreferredSize(new java.awt.Dimension(200, 300));

        txtSOHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSOHD.setMaximumSize(new java.awt.Dimension(2147483647, 60));
        txtSOHD.setPreferredSize(new java.awt.Dimension(7, 28));

        lbSOHD.setBackground(new java.awt.Color(255, 255, 255));
        lbSOHD.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lbSOHD.setForeground(new java.awt.Color(40, 60, 82));
        lbSOHD.setText("SOHD");
        lbSOHD.setPreferredSize(new java.awt.Dimension(28, 14));

        lbMAPHIEUTP.setBackground(new java.awt.Color(255, 255, 255));
        lbMAPHIEUTP.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lbMAPHIEUTP.setForeground(new java.awt.Color(40, 60, 82));
        lbMAPHIEUTP.setText("MAPHIEUTP");
        lbMAPHIEUTP.setPreferredSize(new java.awt.Dimension(35, 14));

        lbMAPHIEUTDV.setBackground(new java.awt.Color(255, 255, 255));
        lbMAPHIEUTDV.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lbMAPHIEUTDV.setForeground(new java.awt.Color(40, 60, 82));
        lbMAPHIEUTDV.setText("MAPHIEUTDV");
        lbMAPHIEUTDV.setPreferredSize(new java.awt.Dimension(38, 14));

        txtMAPHIEUTDV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMAPHIEUTDV.setMaximumSize(new java.awt.Dimension(2147483647, 60));
        txtMAPHIEUTDV.setMinimumSize(new java.awt.Dimension(7, 23));
        txtMAPHIEUTDV.setPreferredSize(new java.awt.Dimension(7, 23));

        txtMAPHIEUTP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMAPHIEUTP.setMaximumSize(new java.awt.Dimension(2147483647, 60));
        txtMAPHIEUTP.setPreferredSize(new java.awt.Dimension(7, 28));

        choosePanel.setBackground(new java.awt.Color(255, 255, 255));
        choosePanel.setLayout(new javax.swing.BoxLayout(choosePanel, javax.swing.BoxLayout.PAGE_AXIS));
        choosePanel.add(filler6);

        addButton.setBackground(new java.awt.Color(255, 255, 255));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanli_khach_san/drawable/add-icon-1.png"))); // NOI18N
        addButton.setBorder(null);
        addButton.setMaximumSize(new java.awt.Dimension(100, 33));
        addButton.setMinimumSize(new java.awt.Dimension(33, 33));
        addButton.setPreferredSize(new java.awt.Dimension(33, 33));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        choosePanel.add(addButton);
        choosePanel.add(filler3);

        editButton.setBackground(new java.awt.Color(255, 255, 255));
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanli_khach_san/drawable/Actions-document-edit-icon-32.png"))); // NOI18N
        editButton.setBorder(null);
        editButton.setMaximumSize(new java.awt.Dimension(100, 31));
        editButton.setMinimumSize(new java.awt.Dimension(32, 32));
        editButton.setPreferredSize(new java.awt.Dimension(32, 32));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        choosePanel.add(editButton);
        choosePanel.add(filler4);

        removeButton.setBackground(new java.awt.Color(255, 255, 255));
        removeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanli_khach_san/drawable/Actions-edit-delete-icon-32.png"))); // NOI18N
        removeButton.setBorder(null);
        removeButton.setMaximumSize(new java.awt.Dimension(100, 31));
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        choosePanel.add(removeButton);
        choosePanel.add(filler5);

        resetButton.setBackground(new java.awt.Color(255, 255, 255));
        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanli_khach_san/drawable/new-icon-1.png"))); // NOI18N
        resetButton.setBorder(null);
        resetButton.setMaximumSize(new java.awt.Dimension(100, 31));
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        choosePanel.add(resetButton);
        choosePanel.add(filler7);

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanli_khach_san/drawable/search-icon-32.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lbMAKM.setBackground(new java.awt.Color(255, 255, 255));
        lbMAKM.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lbMAKM.setForeground(new java.awt.Color(40, 60, 82));
        lbMAKM.setText("MAKM");
        lbMAKM.setPreferredSize(new java.awt.Dimension(28, 14));

        txtMAKM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMAKM.setMaximumSize(new java.awt.Dimension(2147483647, 60));
        txtMAKM.setPreferredSize(new java.awt.Dimension(7, 28));

        lbMANV.setBackground(new java.awt.Color(255, 255, 255));
        lbMANV.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lbMANV.setForeground(new java.awt.Color(40, 60, 82));
        lbMANV.setText("MANV");
        lbMANV.setPreferredSize(new java.awt.Dimension(38, 14));

        txtMANV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMANV.setMaximumSize(new java.awt.Dimension(2147483647, 60));
        txtMANV.setMinimumSize(new java.awt.Dimension(7, 23));
        txtMANV.setPreferredSize(new java.awt.Dimension(7, 23));

        lbNGAYHD.setBackground(new java.awt.Color(255, 255, 255));
        lbNGAYHD.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lbNGAYHD.setForeground(new java.awt.Color(40, 60, 82));
        lbNGAYHD.setText("NGAYHD");
        lbNGAYHD.setPreferredSize(new java.awt.Dimension(28, 14));

        lbMAKH.setBackground(new java.awt.Color(255, 255, 255));
        lbMAKH.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lbMAKH.setForeground(new java.awt.Color(40, 60, 82));
        lbMAKH.setText("MAKM");
        lbMAKH.setPreferredSize(new java.awt.Dimension(28, 14));

        txtMAKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMAKH.setMaximumSize(new java.awt.Dimension(2147483647, 60));
        txtMAKH.setPreferredSize(new java.awt.Dimension(7, 28));

        lbTHANHTIEN.setBackground(new java.awt.Color(255, 255, 255));
        lbTHANHTIEN.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lbTHANHTIEN.setForeground(new java.awt.Color(40, 60, 82));
        lbTHANHTIEN.setText("THANHTIEN");
        lbTHANHTIEN.setPreferredSize(new java.awt.Dimension(28, 14));

        txtTHANHTIEN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTHANHTIEN.setMaximumSize(new java.awt.Dimension(2147483647, 60));
        txtTHANHTIEN.setPreferredSize(new java.awt.Dimension(7, 28));

        javax.swing.GroupLayout informationPanelLayout = new javax.swing.GroupLayout(informationPanel);
        informationPanel.setLayout(informationPanelLayout);
        informationPanelLayout.setHorizontalGroup(
            informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMANV, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(informationPanelLayout.createSequentialGroup()
                        .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMANV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(lbSOHD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMAPHIEUTP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMAPHIEUTP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSOHD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMAPHIEUTDV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbMAPHIEUTDV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(informationPanelLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbMAKM, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                    .addComponent(txtMAKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(informationPanelLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbTHANHTIEN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                        .addComponent(txtTHANHTIEN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbNGAYHD, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dateNGAYHD, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbMAKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMAKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(choosePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        informationPanelLayout.setVerticalGroup(
            informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informationPanelLayout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(choosePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(informationPanelLayout.createSequentialGroup()
                        .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(informationPanelLayout.createSequentialGroup()
                                .addComponent(lbSOHD, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSOHD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(informationPanelLayout.createSequentialGroup()
                                .addComponent(lbMAKM, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMAKM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(informationPanelLayout.createSequentialGroup()
                                .addComponent(lbMAPHIEUTP, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMAPHIEUTP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(informationPanelLayout.createSequentialGroup()
                                .addComponent(lbMAKH, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMAKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informationPanelLayout.createSequentialGroup()
                                .addComponent(lbMAPHIEUTDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMAPHIEUTDV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informationPanelLayout.createSequentialGroup()
                                .addComponent(lbNGAYHD, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateNGAYHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(informationPanelLayout.createSequentialGroup()
                                .addComponent(lbMANV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMANV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(informationPanelLayout.createSequentialGroup()
                                .addComponent(lbTHANHTIEN, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTHANHTIEN, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(informationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(titilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelDVLayout = new javax.swing.GroupLayout(jPanelDV);
        jPanelDV.setLayout(jPanelDVLayout);
        jPanelDVLayout.setHorizontalGroup(
            jPanelDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDVLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDVLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelDVLayout.setVerticalGroup(
            jPanelDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDVLayout.createSequentialGroup()
                .addContainerGap(458, Short.MAX_VALUE)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(jPanelDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDVLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(394, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:

        int row = this.table.getSelectedRow();
        this.txtSOHD.setText(table.getValueAt(row, 0).toString());
        this.txtMAPHIEUTP.setText(table.getValueAt(row, 1).toString());
        this.txtMAPHIEUTDV.setText(table.getValueAt(row, 2).toString());
        this.txtMANV.setText(table.getValueAt(row, 3).toString());
        this.txtMAKM.setText(table.getValueAt(row, 4).toString());
        this.txtMAKH.setText(table.getValueAt(row, 5).toString());
        this.dateNGAYHD.setDate((java.util.Date) table.getValueAt(row, 6));
        this.txtTHANHTIEN.setText(table.getValueAt(row, 7).toString());

    }//GEN-LAST:event_tableMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:


        HoaDon hd= creatNewHoaDon();
        list.add(hd);
        if (txtSOHD.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "SOHD không được để trống", "Lỗi", 1);
        } else {
            int thong_bao = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn thêm dữ liệu này không? ", "Thêm", JOptionPane.YES_NO_OPTION);
            if (thong_bao == JOptionPane.YES_OPTION) {

                HDDAO.insertDatabase(hd);
                pushDataToTable();
                JOptionPane.showMessageDialog(null, "Dữ liệu đã được cập nhật", "Cập nhật", 1);
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:


        HoaDon hd= creatNewHoaDon();
        if (txtSOHD.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "SOHD không được để trống", "Lỗi", 1);
        } else {
            int thong_bao = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn sửa dữ liệu này không? ", "Thêm", JOptionPane.YES_NO_OPTION);
            if (thong_bao == JOptionPane.YES_OPTION) {
                if (HDDAO.updateDatabase(hd)) {
                    list.removeAll(list);
                    list = HDDAO.queryAllHoaDon();
                    pushDataToTable();
                    JOptionPane.showMessageDialog(null, "Dữ liệu đã được cập nhật", "Cập nhật", 1);
                } else {
                    JOptionPane.showMessageDialog(null, "Dữ liệu không được cập nhật", "Cập nhật", 2);
                }
            }

            pushDataToTable();
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:

        try {
            HoaDon hd= creatNewHoaDon();
            if (txtSOHD.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "MADV không được để trống", "Lỗi", 1);
            } else {
                int thong_bao = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa dữ liệu này không? ", "Xóa", JOptionPane.YES_NO_OPTION);

                if (thong_bao == JOptionPane.YES_OPTION) {
                    if (HDDAO.deleteDatabase(hd)) {
                        //listDV.remove(listDV.indexOf(dv));
                        list.removeAll(list);
                        list = HDDAO.queryAllHoaDon();
                        list.remove(hd);
                        pushDataToTable();

                        JOptionPane.showMessageDialog(null, "Dữ liệu đã được xóa", "Xóa", 1);
                    } else {
                        JOptionPane.showMessageDialog(null, "Dữ liệu không xóa được", "Xóa", 2);
                    }
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage() + "Chọn thông tin khách hàng muốn xóa.", " Thông báo.", 1);
        }

        pushDataToTable();
    }//GEN-LAST:event_removeButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:

        list.removeAll(list);
        list = HDDAO.queryAllHoaDon();
        pushDataToTable();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        HoaDon hd= creatNewHoaDon();

        list.removeAll(list);
        list = HDDAO.queryAllHoaDon();
        pushDataToTable();

        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Không tìm thấy dữ liệu cần tìm.", "Thông báo", 1);
        }


    }//GEN-LAST:event_btnSearchActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel choosePanel;
    private com.toedter.calendar.JDateChooser dateNGAYHD;
    private javax.swing.JButton editButton;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JPanel informationPanel;
    private javax.swing.JPanel jPanelDV;
    private javax.swing.JLabel lbMAKH;
    private javax.swing.JLabel lbMAKM;
    private javax.swing.JLabel lbMANV;
    private javax.swing.JLabel lbMAPHIEUTDV;
    private javax.swing.JLabel lbMAPHIEUTP;
    private javax.swing.JLabel lbNGAYHD;
    private javax.swing.JLabel lbSOHD;
    private javax.swing.JLabel lbTHANHTIEN;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tablePanel;
    private javax.swing.JPanel titilePanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField txtMAKH;
    private javax.swing.JTextField txtMAKM;
    private javax.swing.JTextField txtMANV;
    private javax.swing.JTextField txtMAPHIEUTDV;
    private javax.swing.JTextField txtMAPHIEUTP;
    private javax.swing.JTextField txtSOHD;
    private javax.swing.JTextField txtTHANHTIEN;
    // End of variables declaration//GEN-END:variables
}
