/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanli_khach_san.homepage;

import quanli_khach_san.dichvu.DichVuFrameNew;
import quanli_khach_san.hoadon.HoaDonFrame;
import quanli_khach_san.hoadon.HoaDonFrameNew;
import quanli_khach_san.khachhang.KhachHangFrame;
import quanli_khach_san.khuyenmai.KhuyenMaiFrame;
import quanli_khach_san.nhanvien.NhanVienFrame;
import quanli_khach_san.phong.ChonPhong;
import quanli_khach_san.phong.Phong;
import quanli_khach_san.quydinh.QuyDinh;
import quanli_khach_san.taikhoan.TaiKhoanFrame;

/**
 * @author HP
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        TongQuan tq= new TongQuan();
        HoaDonFrameNew hdf=new HoaDonFrameNew();
        tq.setHDFtoTQF(hdf);
        hdf.setTQFtoHDF(tq);
        jPanelDV = new DichVuFrameNew().getPanel();
        jPanelHD = hdf.getPanel();
        jPanelKH = new KhachHangFrame().getPanel();
        jPanelKM = new KhuyenMaiFrame().getPanel();
        jPanelNV = new NhanVienFrame().getPanel();
        jPanelP = tq.getPanel();
        jPanelQD = new QuyDinh().getPanel();
        jPanelTK = new TaiKhoanFrame().getPanel();

        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1550, 768));

        jTabbedPane5.setBackground(new java.awt.Color(85, 120, 204));
        jTabbedPane5.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTabbedPane5.setMinimumSize(new java.awt.Dimension(350, 150));
        jTabbedPane5.setPreferredSize(new java.awt.Dimension(700, 600));


        jTabbedPane5.addTab("Tổng quan phòng       ", new javax.swing.ImageIcon(getClass().getResource("/quanli_khach_san/icon/phong2.png")), jPanelP); // NOI18N


        jTabbedPane5.addTab("Quản lý hóa đơn         ", new javax.swing.ImageIcon(getClass().getResource("/quanli_khach_san/icon/hoadon1.png")), jPanelHD); // NOI18N

        jTabbedPane5.addTab("Quản lý khách hàng       ", new javax.swing.ImageIcon(getClass().getResource("/quanli_khach_san/icon/khachhang.png")), jPanelKH); // NOI18N

        jTabbedPane5.addTab("Quản lý khuyến mãi         ", new javax.swing.ImageIcon(getClass().getResource("/quanli_khach_san/icon/giamgia.png")), jPanelKM); // NOI18N


        jTabbedPane5.addTab("Quản lý dịch vụ           ", new javax.swing.ImageIcon(getClass().getResource("/quanli_khach_san/icon/dichvu.png")), jPanelDV); // NOI18N


        jTabbedPane5.addTab("Quản lý nhân viên          ", new javax.swing.ImageIcon(getClass().getResource("/quanli_khach_san/icon/nhanvien.png")), jPanelNV); // NOI18N


        jTabbedPane5.addTab("Báo cáo thống kê        ", new javax.swing.ImageIcon(getClass().getResource("/quanli_khach_san/icon/baocao1.png")), jPanelBCTK); // NOI18N


        jTabbedPane5.addTab("Quy định khách sạn       ", new javax.swing.ImageIcon(getClass().getResource("/quanli_khach_san/icon/quydinh.png")), jPanelQD); // NOI18N


        jTabbedPane5.addTab("Thông tin tài khoản     ", new javax.swing.ImageIcon(getClass().getResource("/quanli_khach_san/icon/taikhoan.png")), jPanelTK); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelBCTK;
    private javax.swing.JPanel jPanelDV;
    private javax.swing.JPanel jPanelHD;
    private javax.swing.JPanel jPanelKH;
    private javax.swing.JPanel jPanelKM;
    private javax.swing.JPanel jPanelNV;
    private javax.swing.JPanel jPanelP;
    private javax.swing.JPanel jPanelQD;
    private javax.swing.JPanel jPanelTK;
    private javax.swing.JTabbedPane jTabbedPane5;
    // End of variables declaration//GEN-END:variables
}
