/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package quanli_khach_san;

import java.util.logging.Logger;
import java.util.logging.Level;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.table.JTableHeader;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.border.Border;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import java.awt.Font;
import java.awt.Component;
import javax.swing.JComponent;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import java.util.Calendar;
public class KhuyenMai extends javax.swing.JFrame {

    /** Creates new form KhuyenMai */
    public KhuyenMai() {
        initComponents();
        this.table.getTableHeader().setFont(new Font("Courier New",Font.PLAIN,15));
        this.table.getTableHeader().setOpaque(false);
        this.table.getTableHeader().setBackground(new Color(40,60,82));
        this.table.getTableHeader().setForeground(Color.WHITE);
        this.table.setRowHeight(25);
        
        this.pushDataToTable();
    }
     public void pushDataToTable(){
        Discount km = new Discount();
        ArrayList<Discount> ListKM = km.ListKM();
        
        String[] ColumnName = {"MAKM","TENKM","NGAYBD","NGAYKT"};
        Object[][] Rows = new Object[ListKM.size()][4];
        for(int i = 0; i < ListKM.size(); i ++){
            Rows[i][0] = ListKM.get(i).getMAKM();
            Rows[i][1] = ListKM.get(i).getTENKM();
            Rows[i][2] = ListKM.get(i).getNgayBD();
            Rows[i][3] = ListKM.get(i).getNgayKT();
        }
        DefaultTableModel model = new DefaultTableModel(Rows,ColumnName);
        this.table.setModel(model);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(50, 32767));
        searchButton = new javax.swing.JButton();
        interactionPanel = new javax.swing.JPanel();
        inputPanel = new javax.swing.JPanel();
        idTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        startDateJDchoose = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        finishDateJDchoose = new com.toedter.calendar.JDateChooser();
        buttonPanel = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 32767));
        jButton_add = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jButton_edit = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jButton_remove = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        resetButton = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 32767));
        tablePanel = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(716, 712));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.PAGE_AXIS));

        titlePanel.setBackground(new java.awt.Color(40, 60, 82));
        titlePanel.setMaximumSize(new java.awt.Dimension(32767, 80));
        titlePanel.setMinimumSize(new java.awt.Dimension(0, 60));
        titlePanel.setPreferredSize(new java.awt.Dimension(716, 60));
        titlePanel.setLayout(new javax.swing.BoxLayout(titlePanel, javax.swing.BoxLayout.LINE_AXIS));

        titleLabel.setBackground(new java.awt.Color(255, 255, 255));
        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("QUẢN LÍ THÔNG TIN KHUYẾN MÃI");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titleLabel.setMaximumSize(new java.awt.Dimension(3200000, 100));
        titlePanel.add(titleLabel);

        mainPanel.add(titlePanel);

        searchPanel.setBackground(new java.awt.Color(255, 255, 255));
        searchPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 50, 10, 50));
        searchPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        searchPanel.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        searchPanel.setMinimumSize(new java.awt.Dimension(184, 60));
        searchPanel.setPreferredSize(new java.awt.Dimension(716, 60));
        searchPanel.setLayout(new javax.swing.BoxLayout(searchPanel, javax.swing.BoxLayout.LINE_AXIS));

        searchTextField.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        searchTextField.setForeground(new java.awt.Color(102, 102, 102));
        searchTextField.setText("Nhập thông tin cần tìm vào đây.");
        searchTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(40, 60, 82)));
        searchTextField.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        searchTextField.setMinimumSize(new java.awt.Dimension(100, 30));
        searchTextField.setPreferredSize(new java.awt.Dimension(120, 20));
        searchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusLost(evt);
            }
        });
        searchPanel.add(searchTextField);
        searchPanel.add(filler1);

        searchButton.setBackground(new java.awt.Color(255, 255, 255));
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Pictures\\loupe.png")); // NOI18N
        searchButton.setBorder(null);
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        searchPanel.add(searchButton);

        mainPanel.add(searchPanel);

        interactionPanel.setBackground(new java.awt.Color(255, 255, 255));
        interactionPanel.setLayout(new javax.swing.BoxLayout(interactionPanel, javax.swing.BoxLayout.LINE_AXIS));

        inputPanel.setBackground(new java.awt.Color(255, 255, 255));

        idTextField.setEditable(false);
        idTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idTextField.setToolTipText("");
        idTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        idTextField.setFocusable(false);
        idTextField.setOpaque(false);

        nameTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        nameTextField.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 60, 82));
        jLabel2.setText("MAKM*");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(40, 60, 82));
        jLabel3.setText("TENKM");

        startDateJDchoose.setBackground(new java.awt.Color(255, 255, 255));
        startDateJDchoose.setToolTipText("");
        startDateJDchoose.setDate(new java.util.Date(1622276522000L));
        startDateJDchoose.setDateFormatString("yyyy-MM-dd");
        startDateJDchoose.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 60, 82));
        jLabel1.setText("NGAYBD");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(40, 60, 82));
        jLabel4.setText("NGAYKT");

        finishDateJDchoose.setDateFormatString("yyyy-MM-dd");

        org.jdesktop.layout.GroupLayout inputPanelLayout = new org.jdesktop.layout.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(inputPanelLayout.createSequentialGroup()
                .add(31, 31, 31)
                .add(inputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(idTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 245, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)
                    .add(nameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 245, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 40, Short.MAX_VALUE)
                .add(inputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, finishDateJDchoose, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel4)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, startDateJDchoose, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(inputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(inputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(startDateJDchoose, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(idTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .add(inputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(inputPanelLayout.createSequentialGroup()
                        .add(27, 27, 27)
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, inputPanelLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel3)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(inputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(nameTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .add(finishDateJDchoose, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(60, 60, 60))
        );

        interactionPanel.add(inputPanel);

        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));
        buttonPanel.setMaximumSize(new java.awt.Dimension(300, 65720));
        buttonPanel.setPreferredSize(new java.awt.Dimension(100, 250));
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.PAGE_AXIS));
        buttonPanel.add(filler4);

        jButton_add.setBackground(new java.awt.Color(255, 255, 255));
        jButton_add.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jButton_add.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Pictures\\add.png")); // NOI18N
        jButton_add.setToolTipText("");
        jButton_add.setBorder(null);
        jButton_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_add.setMaximumSize(new java.awt.Dimension(100, 31));
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });
        buttonPanel.add(jButton_add);
        buttonPanel.add(filler2);

        jButton_edit.setBackground(new java.awt.Color(255, 255, 255));
        jButton_edit.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jButton_edit.setForeground(new java.awt.Color(255, 255, 255));
        jButton_edit.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Pictures\\edit (1).png")); // NOI18N
        jButton_edit.setBorder(null);
        jButton_edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_edit.setMaximumSize(new java.awt.Dimension(100, 31));
        jButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editActionPerformed(evt);
            }
        });
        buttonPanel.add(jButton_edit);
        buttonPanel.add(filler3);

        jButton_remove.setBackground(new java.awt.Color(255, 255, 255));
        jButton_remove.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jButton_remove.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Pictures\\001-bin.png")); // NOI18N
        jButton_remove.setBorder(null);
        jButton_remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_remove.setMaximumSize(new java.awt.Dimension(100, 31));
        jButton_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_removeActionPerformed(evt);
            }
        });
        buttonPanel.add(jButton_remove);
        buttonPanel.add(filler5);

        resetButton.setBackground(new java.awt.Color(255, 255, 255));
        resetButton.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        resetButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Pictures\\loop.png")); // NOI18N
        resetButton.setBorder(null);
        resetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetButton.setMaximumSize(new java.awt.Dimension(100, 31));
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(resetButton);
        buttonPanel.add(filler6);

        interactionPanel.add(buttonPanel);

        mainPanel.add(interactionPanel);

        getContentPane().add(mainPanel);

        table.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MAKM", "TENKM", "NGAYBD", "NGAYKT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        tablePanel.setViewportView(table);

        getContentPane().add(tablePanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusGained
        // TODO add your handling code here:
        if(searchTextField.getText().equals("Nhập thông tin cần tìm vào đây.")){
            searchTextField.setText("");
        }
    
    }//GEN-LAST:event_searchTextFieldFocusGained

    private void searchTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusLost
        // TODO add your handling code here:
         if(searchTextField.getText().equals("")){
            searchTextField.setText("Nhập thông tin cần tìm vào đây.");
        }
       

    }//GEN-LAST:event_searchTextFieldFocusLost

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        try{
            int row = this.table.getSelectedRow();
            this.idTextField.setText(table.getValueAt(row,0).toString());
            this.nameTextField.setText(table.getValueAt(row,1).toString());      
            Date startdate = new SimpleDateFormat("yyyy-MM-dd").parse(table.getValueAt(row, 2).toString());
            startDateJDchoose.setDate(startdate);
            Date finishdate = new SimpleDateFormat("yyyy-MM-dd").parse(table.getValueAt(row, 3).toString());
            finishDateJDchoose.setDate(finishdate);
        }catch (ParseException ex) {
            Logger.getLogger(Discount.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }//GEN-LAST:event_tableMouseClicked

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        try{
            String tenkm = this.nameTextField.getText();
            String startdate = dateFormat.format(startDateJDchoose.getDate());
            Date ngaybd = dateFormat.parse(startdate);
            java.sql.Date sqlngbd = new java.sql.Date(ngaybd.getTime());             
            String finishdate = dateFormat.format(finishDateJDchoose.getDate());
            Date ngaykt = dateFormat.parse(finishdate);
            java.sql.Date sqlngkt = new java.sql.Date(ngaykt.getTime());
 
            Discount km = new Discount(tenkm, sqlngbd, sqlngkt);
            int thong_bao = JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn thêm dữ liệu này không? ","Thêm",JOptionPane.YES_NO_OPTION);
            if(thong_bao == JOptionPane.YES_OPTION){
                if(tenkm.isEmpty()){
                    JOptionPane.showMessageDialog(null,"Nhập thông tin khuyến mãi.","Bạn chưa nhập đầy đủ thông tin.",2);
                }
                if (km.insert(km)){
                     JOptionPane.showMessageDialog(null,"Dữ liệu đã được thêm.","Thêm",1);
                }
                else{
                     JOptionPane.showMessageDialog(null,"Dữ liệu không thêm được.","Thêm",2);
                }
              }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage() + "Nhập thông tin khuyến mãi muốn thêm."," Thông báo.",1);
        }
            pushDataToTable();
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        try{
            String id = this.idTextField.getText();
            String tenkm = this.nameTextField.getText();
            String startdate = dateFormat.format(startDateJDchoose.getDate());
            Date ngaybd = dateFormat.parse(startdate);
            java.sql.Date sqlngbd = new java.sql.Date(ngaybd.getTime());             
            String finishdate = dateFormat.format(finishDateJDchoose.getDate());
            Date ngaykt = dateFormat.parse(finishdate);
            java.sql.Date sqlngkt = new java.sql.Date(ngaykt.getTime());
            Discount km = new Discount(id, tenkm, sqlngbd, sqlngkt);
            int thong_bao = JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn cập nhật dữ liệu này không? ","Cập nhật",JOptionPane.YES_NO_OPTION);
            if(thong_bao == JOptionPane.YES_OPTION){
                if(tenkm.isEmpty()){
                    JOptionPane.showMessageDialog(null,"Nhập thông tin khuyến mãi.","Bạn chưa nhập đầy đủ thông tin.",2);
                }
                if (km.update(km)){
                     JOptionPane.showMessageDialog(null,"Dữ liệu đã được cập nhật","Cập nhật",1);
                }
                else{
                     JOptionPane.showMessageDialog(null,"Dữ liệu không được cập nhật","Cập nhật",2);
                }
              }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage() + "Nhập thông tin khuyến mãi muốn cập nhật."," Thông báo.",1);
        }
            pushDataToTable();
    }//GEN-LAST:event_jButton_editActionPerformed

    private void jButton_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removeActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        try{
            String id = this.idTextField.getText();
            String tenkm = this.nameTextField.getText();
            String startdate = dateFormat.format(startDateJDchoose.getDate());
            Date ngaybd = dateFormat.parse(startdate);
            java.sql.Date sqlngbd = new java.sql.Date(ngaybd.getTime());             
            String finishdate = dateFormat.format(finishDateJDchoose.getDate());
            Date ngaykt = dateFormat.parse(finishdate);
            java.sql.Date sqlngkt = new java.sql.Date(ngaykt.getTime());
            Discount km = new Discount(id, tenkm, sqlngbd, sqlngkt);
      
            int thong_bao = JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn xóa " +
                    tenkm + " dữ liệu này không? ","Xóa",JOptionPane.YES_NO_OPTION);
            if(thong_bao == JOptionPane.YES_OPTION){
                if (km.delete(km)){
                     JOptionPane.showMessageDialog(null,"Dữ liệu đã được xóa","Xóa",1);     
                }
                else{
                     JOptionPane.showMessageDialog(null,"Dữ liệu không xóa được","Xóa",2);
                }
              }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage() + "Chọn thông tin khách hàng muốn xóa."," Thông báo.",1);
        }
        
        pushDataToTable();
    }//GEN-LAST:event_jButton_removeActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        Discount nv = new Discount();
        String input = this.searchTextField.getText();
        
        ArrayList<Discount> ListName = nv.ListName(input);
        String[] ColumnName = {"MAKM","TENKM","NGAYBD","NGAYKT"};
        Object[][] Rows = new Object[ListName.size()][4];
        for(int i = 0; i < ListName.size(); i ++){
            Rows[i][0] = ListName.get(i).getMAKM();
            Rows[i][1] = ListName.get(i).getTENKM();
            Rows[i][2] = ListName.get(i).getNgayBD();
            Rows[i][3] = ListName.get(i).getNgayKT();
        }
        DefaultTableModel model = new DefaultTableModel(Rows,ColumnName);
        this.table.setModel(model);  
  
        int rows = table.getRowCount();
        if(rows == 0){
            JOptionPane.showMessageDialog(null,"Không tìm thấy dữ liệu cần tìm.","Thông báo",1);
            pushDataToTable();
        }
           
    }//GEN-LAST:event_searchButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
       try{
            if(!this.idTextField.getText().equals("")
                    || !this.nameTextField.getText().equals("")
                    || !this.searchTextField.getText().equals("Nhập thông tin cần kiếm vào đây."))
            {
                this.idTextField.setText("");
                this.nameTextField.setText("");
                this.searchTextField.setText("Nhập thông tin cần tìm vào đây.");
                String today = "2021-05-26";
                Date startdate = new SimpleDateFormat("yyyy-MM-dd").parse(today);
                startDateJDchoose.setDate(startdate);
                Date finishdate = new SimpleDateFormat("yyyy-MM-dd").parse(today);
                finishDateJDchoose.setDate(finishdate);

                pushDataToTable();
            }
        }catch (ParseException ex) {
            Logger.getLogger(Discount.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhuyenMai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private com.toedter.calendar.JDateChooser finishDateJDchoose;
    private javax.swing.JTextField idTextField;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JPanel interactionPanel;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_edit;
    private javax.swing.JButton jButton_remove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTextField;
    private com.toedter.calendar.JDateChooser startDateJDchoose;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tablePanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables

}
