/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanli_khach_san.quydinh;

import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class QuyDinh extends javax.swing.JFrame {

    /**
     * Creates new form QuyDinh
     */
    public QuyDinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        qdnv = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        qdkm = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        qdp = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        qddv = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        qdhd = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUY ĐỊNH KHÁCH SẠN ÁNH DƯƠNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N

        qdnv.setColumns(20);
        qdnv.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        qdnv.setRows(5);
        qdnv.setText("1. Mỗi nhân viên được cấp một tài khoản để đăng nhập vào hệ thống\n2.Nhân viên đảm bảo đi làm đúng giờ, mặc đúng đồng phục khách sạn đã cung cấp");
        qdnv.setEnabled(false);
        jScrollPane1.setViewportView(qdnv);

        jTabbedPane1.addTab("Quy định nhân viên", jScrollPane1);

        qdkm.setColumns(20);
        qdkm.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        qdkm.setRows(5);
        qdkm.setText("1.Khuyến mãi sẽ được quản lý bởi người quản lý, nhân viên chỉ có quyền xem các thông tin khuyến mãi mà không được sửa đổi.\n2.Khuyến mãi sẽ áp dụng theo 2 hình thức: khuyến mãi theo loại khách hàng, khuyến mãi theo ngày lễ lớn.");
        qdkm.setEnabled(false);
        jScrollPane5.setViewportView(qdkm);

        jTabbedPane1.addTab("Quy định khuyến mãi", jScrollPane5);

        qdp.setColumns(20);
        qdp.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        qdp.setRows(5);
        qdp.setText("1. Có hai loại phòng là đôi và đơn\n2. Khi số người thuê vượt số người của loại phòng đó thì cứ thêm 1 người phụ thu là 20% giá phòng đó.\n(Ví dụ 2 khách thuê 1 phòng đơn thì giá phòng là 120% giá niêm yết.)\n3. Một khách hàng có thể 1 lúc thuê được nhiều phòng\n\n\n");
        qdp.setEnabled(false);
        jScrollPane6.setViewportView(qdp);

        jTabbedPane1.addTab("Quy định phòng", jScrollPane6);

        qddv.setColumns(20);
        qddv.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        qddv.setRows(5);
        qddv.setText("1. Khi khách đặt thuê phòng thì mới được thuê dịch vụ.");
        qddv.setEnabled(false);
        jScrollPane7.setViewportView(qddv);

        jTabbedPane1.addTab("Quy định dịch vụ", jScrollPane7);

        qdhd.setColumns(20);
        qdhd.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        qdhd.setRows(5);
        qdhd.setText("1. Khi khách hàng thuê phòng thì 1 hóa đơn sẽ được tạo trước, kèm theo phiếu thuê phòng chứa thông tin các phòng được thuê và phiếu dịch vụ (nếu có) \nchứa thông tin các dịch vụ được thuê.");
        qdhd.setEnabled(false);
        jScrollPane4.setViewportView(qdhd);

        jTabbedPane1.addTab("Quy định hóa đơn", jScrollPane4);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getPanel()
    {
        return jPanel6;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuyDinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuyDinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuyDinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuyDinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuyDinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea qddv;
    private javax.swing.JTextArea qdhd;
    private javax.swing.JTextArea qdkm;
    private javax.swing.JTextArea qdnv;
    private javax.swing.JTextArea qdp;
    // End of variables declaration//GEN-END:variables
}
